steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - ${_DOCKERFILE}
      - --tag
      - ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}
      - .

images:
  - ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}
