require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const swaggerUi = require('swagger-ui-express');
const swaggerSpec = require('./swagger/swagger');
const orderRoutes = require('./routes/order.routes');
const cartRoutes = require('./routes/cart.routes');
const publicCartRoutes = require('./routes/public-cart.routes');
const shoppingRoutes = require('./routes/shopping.routes');
const giftingRoutes = require('./routes/gifting.routes');
const giftingCartRoutes = require('./routes/gifting-cart.routes');
const vendorOrderRoutes = require('./routes/vendor-order.routes');
const errorHandler = require('../../../shared/middlewares/error.middleware');

const app = express();
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan('dev'));
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'order-service' }));
app.use('/api/cart', publicCartRoutes);
app.use('/api/shop', shoppingRoutes);
app.use('/api/gifting/cart', giftingCartRoutes);
app.use('/api/gifting', giftingRoutes);
app.use('/api/orders/cart', cartRoutes);
app.use('/api/vendor/orders', vendorOrderRoutes);
app.use('/api/orders', orderRoutes);
app.use((req, res) => res.status(404).json({ success: false, message: 'Route not found' }));
app.use(errorHandler);
module.exports = app;
